on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v3.1.18
      - uses: actions/checkout@v4
        with:
          # until https://github.com/actions/checkout/pull/579 is released
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.1"
      - name: Build
        run: |
          make policy.wasm
      - name: Annotate
        run: |
          make annotated-policy.wasm
      - name: Run e2e tests
        run: |
          make e2e-tests
